--DROP TABLE following;
--DROP TABLE favorites;
--DROP TABLE comment;
--DROP TABLE conversation;
--DROP TABLE sale;
--DROP TABLE collectionimage;
--DROP TABLE productimage;
--DROP TABLE collectiontag;
--DROP TABLE producttag;
--DROP TABLE shoptag;
--DROP TABLE tag;
--DROP TABLE shoprating;
--DROP TABLE product;
--DROP TABLE collection;
--DROP TABLE shop;
--DROP TABLE region;
--DROP TABLE person;

--DROP SEQUENCE shop_id_seq;
--DROP SEQUENCE shoprating_id_seq;
--DROP SEQUENCE tag_id_seq;
--DROP SEQUENCE product_id_seq;
--DROP SEQUENCE productimage_id_seq;
--DROP SEQUENCE sale_id_seq;
--DROP SEQUENCE conversation_id_seq;
--DROP SEQUENCE comment_id_seq;
--DROP SEQUENCE favorites_id_seq;
--DROP SEQUENCE following_id_seq;

--CREATE SEQUENCE shop_id_seq 			INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
--CREATE SEQUENCE shoprating_id_seq 		INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
--CREATE SEQUENCE tag_id_seq 				INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
--CREATE SEQUENCE product_id_seq 			INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
--CREATE SEQUENCE productimage_id_seq 	INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
--CREATE SEQUENCE sale_id_seq 			INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
--CREATE SEQUENCE conversation_id_seq 	INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
--CREATE SEQUENCE comment_id_seq 			INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
--CREATE SEQUENCE favorites_id_seq 		INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
--CREATE SEQUENCE following_id_seq 		INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE wiki(
 "Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 "title" VARCHAR (50) NOT NULL,
 "intro" VARCHAR (300) NOT NULL,
 "created_on" TIMESTAMP NOT NULL
);
CREATE TABLE chapter(
 "Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 "title" VARCHAR(100) NOT NULL,
 "text" VARCHAR(1000) NOT NULL,
 "priority" INTEGER NOT NULL,
 "wiki_id" INTEGER NOT NULL,
 CONSTRAINT chapter_text_fkey FOREIGN KEY (wiki_id)
      REFERENCES wiki ("Id") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
);
CREATE TABLE reference(
 "Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 "text" VARCHAR(50) NOT NULL,
 "priority" INTEGER NOT NULL,
 "chapter_id" INTEGER NOT NULL,
 CONSTRAINT reference_text_fkey FOREIGN KEY (chapter_id)
      REFERENCES chapter ("Id") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
);
CREATE TABLE image(
 "Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 "name" VARCHAR (50) NOT NULL,
 "created_on" TIMESTAMP NOT NULL,
 "wiki_id" INTEGER,
 CONSTRAINT image_wiki_fkey FOREIGN KEY (wiki_id)
      REFERENCES wiki ("Id") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE,
 "chapter_id" INTEGER,
 CONSTRAINT image_chapter_fkey FOREIGN KEY (chapter_id)
      REFERENCES chapter ("Id") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
);